"""Add longest_streak to user

Revision ID: 1a7434e7538f
Revises: 9c0b15b52449
Create Date: 2025-06-27 23:11:32.565765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7434e7538f'
down_revision = '9c0b15b52449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longest_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('longest_streak')

    # ### end Alembic commands ###
