"""Add duration, estimated_calories, personal_bests

Revision ID: 490aeb0162f9
Revises: eec19b24cd43
Create Date: 2025-06-26 01:41:30.604555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490aeb0162f9'
down_revision = 'eec19b24cd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_bests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('max_reps', sa.Integer(), nullable=True),
    sa.Column('max_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estimated_calories', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('estimated_calories')
        batch_op.drop_column('duration')

    op.drop_table('personal_bests')
    # ### end Alembic commands ###
