"""clean migration

Revision ID: d86b86587977
Revises: 61353397a68c
Create Date: 2025-07-01 19:04:01.828983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd86b86587977'
down_revision = '61353397a68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_bests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_bests_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('date')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('personal_bests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_bests_user_id'))

    # ### end Alembic commands ###
